spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/static/documents/formatos/
      cache:
        period: 3600s

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: America/La_Paz
      # Reactivar validaciones est√°ndar
      hibernate.temp.use_jdbc_metadata_defaults: true

  datasource.hikari:
    maximum-pool-size: 3
    minimum-idle: 1
    idle-timeout: 10000
    connection-timeout: 20000
    max-lifetime: 30000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  resend:
    apikey: ${RESEND_API_KEY}
    
  debug: true

server:
  port: ${PORT:8080}
  time-zone: America/La_Paz
jwt:
  secret: USEI_SUPER_SECRET_KEY_2025_CAMBIA_ESTO_1234567890
