spring:
  web:
    resources:
      #mostrar certificado del estudiante
      static-locations: classpath:/static/, classpath:/static/documents/formatos/
      cache:
        period: 3600s

  mvc:
    throw-exception-if-no-handler-found: true

  # web:
  #   resources:
  #     add-mappings: true

  datasource:
    url: jdbc:postgresql://localhost:5433/proyecto_usei
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: America/La_Paz

  datasource.hikari:
    maximum-pool-size: 1       #  SOLO 1 conexi贸n permitida!!
    minimum-idle: 0
    idle-timeout: 10000
    connection-timeout: 20000
    max-lifetime: 30000

  # resources:
  #   static-locations: classpath:/static/documents/  # Ruta para servir archivos est谩ticos
  #   cache:
  #     period: 3600s  # Cachea los archivos est谩ticos durante una hora

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: pruebasu123@gmail.com
    password: xwnt rmyr axpb bmat
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  debug: true
server:
  port: ${PORT:8080} # Cambia 8081 por el puerto que desees utilizar, puede ser 8081, 9000, etc.
  time-zone: America/La_Paz

# Swagger configuration
springfox:
  documentation:
    swagger-ui:
      base-url: /swagger-ui
    api-docs:
      path: /v2/api-docs

# Configuraci贸n adicional para Swagger
swagger:
  api-info:
    title: "Documentaci贸n de la API de Proyecto USEI"
    description: "Documentaci贸n generada autom谩ticamente con Swagger para Proyecto USEI"
    version: "1.0"

servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
